# Generated by Django 4.0.8 on 2023-03-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_disease_plant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plant_Name', models.CharField(max_length=255)),
                ('features', models.CharField(max_length=255)),
                ('Species', models.TextField()),
                ('Description', models.TextField()),
                ('diseases', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='plant',
            name='diseases',
        ),
        migrations.DeleteModel(
            name='Disease',
        ),
        migrations.DeleteModel(
            name='Plant',
        ),
    ]
