# Generated by Django 4.0.8 on 2023-03-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_diseases_data_diseases_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Description',
            field=models.CharField(max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='data',
            name='Diseases',
            field=models.CharField(max_length=255, verbose_name='Diseases'),
        ),
        migrations.AlterField(
            model_name='data',
            name='Features',
            field=models.CharField(max_length=255, verbose_name='Features'),
        ),
        migrations.AlterField(
            model_name='data',
            name='Plant_Name',
            field=models.CharField(max_length=255, verbose_name='Plant_Name'),
        ),
        migrations.AlterField(
            model_name='data',
            name='Species',
            field=models.CharField(max_length=255, verbose_name='Species'),
        ),
    ]
