# Generated by Django 4.0.8 on 2023-03-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_data_description_alter_data_diseases_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
