# Generated by Django 4.1.7 on 2023-04-26 08:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_data_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
