# Generated by Django 4.1.7 on 2023-04-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_image_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
